name: Vale
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Sphinx

    - name: File Changes
      id: file_changes
      uses: trilom/file-changes-action@v1.2.3

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        files: '${{ steps.file_changes.outputs.files_modified }}'

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
